# Generated by Django 3.0.8 on 2020-12-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.TextField()),
                ('main', models.TextField()),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
    ]
