# Generated by Django 3.0.8 on 2020-12-16 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
