# Generated by Django 3.0.8 on 2020-11-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('phone', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
    ]
