# Generated by Django 3.0.8 on 2020-11-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
