# Generated by Django 3.0.8 on 2020-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201112_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
