# Generated by Django 3.0.8 on 2020-11-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201121_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
