# Generated by Django 3.0.8 on 2020-12-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201122_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('phone', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
    ]
