# Generated by Django 3.0.8 on 2020-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mental', models.FileField(upload_to='')),
                ('money', models.IntegerField()),
            ],
        ),
    ]
